apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: mnist-ddp-dist
  namespace: kubeflow # Adjust if needed
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: docker.io/myusername/mnist-ddp:latest # REPLACE with your actual image
              imagePullPolicy: Always
              command:
                - "python"
                - "src/train_ddp.py"
              resources:
                limits:
                  nvidia.com/gpu: 1 # Remove if running on CPU
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: docker.io/myusername/mnist-ddp:latest # REPLACE with your actual image
              imagePullPolicy: Always
              command:
                - "python"
                - "src/train_ddp.py"
              resources:
                limits:
                  nvidia.com/gpu: 1 # Remove if running on CPU
